config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :decks
  get 'decks/:id/draw', controller: :decks, action: :draw
  get 'decks/:id/draw_3', controller: :decks, action: :draw_3
  root "decks#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards, dependent: :destroy
  accepts_nested_attributes_for :cards, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # respond_to :json, :html, :turbo_stream

  def after_sign_in_path_for(resource)
    decks_path
  end

  # def after_sign_up_path_for(resource)
  #   new_user_session
  # end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!, except: %i[draw index draw_3]
  before_action :set_deck, only: %i[ show edit update destroy draw draw_3 ]

  def draw
    draw = @deck.cards.select{|it| it.enabled }.sample
    respond_to do |format|
      format.html { render html: "<br><span style=\"color:#{draw.color || "black"};font-size:30px;text-align: center\">#{draw.body}</span>".html_safe }
    end
  end

  def draw_3
    draws = @deck.cards.select{|it| it.enabled }.sample(3)
    respond_to do |format|
      html = ("<br>" + draws.each_with_index.map { |draw, i| "<span style=\"color:#{draw.color || "black"};font-size:30px;text-align: center\">#{draw.body}#{((i < 2) && ", ") || ""} </span>"}.join("")).html_safe
      format.html { render html: html }
    end
  end

  # GET /decks or /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1 or /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks or /decks.json
  def create
    @deck = Deck.new(deck_params)
    @deck.slug = @deck.name.downcase.gsub(' ', '-')
    respond_to do |format|
      if @deck.save
        format.html { redirect_to deck_url(@deck), notice: "Deck was successfully created." }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1 or /decks/1.json
  def update
    deck_params[:slug] ||= deck_params[:name].downcase.gsub(' ', '-')
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to deck_url(@deck), notice: "Deck was successfully updated." }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1 or /decks/1.json
  def destroy
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url, notice: "Deck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find_by_slug(params[:id]) if params[:id] =~ /\p{L}/
      @deck ||= Deck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deck_params
      params.require(:deck).permit(:name, :slug, cards_attributes: [:id, :body, :enabled, :color, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_card_js.html.erb
<script type="module">
import{ createApp } from 'vue'
document.addEventListener( 'turbo:render', () => {
  const app = createApp({
      data() {
          return {
              id: this.id,
              deck: this.deck
          }
      },
      created() {
          this.element = document.getElementById('deck-form')
          this.id = this.element.dataset.id
          this.deck = JSON.parse(this.element.dataset.deck)
          this.cards_attributes = JSON.parse(this.element.dataset.cardsAttributes)
          this.cards_attributes.forEach((card) => {
              card._destroy = null
          })
          this.deck.cards_attributes = this.cards_attributes
          console.log("Loaded Component")
      },
      methods: {
          addCard() {
              this.deck.cards_attributes.push({id: null, body: "", enabled: true, _destroy: null})
          },
          removeCard(index) {
              let card = this.deck.cards_attributes[index]
              if (card.id == null) {
                  this.deck.cards_attributes.splice(index, 1)
              } else {
                  this.deck.cards_attributes[index]._destroy = "1"
              }
          },
          undoRemove(index) {
              this.deck.cards_attributes[index]._destroy = null
          },
          saveDeck() {
              if (this.id == null) {
                  const requestOptions = {
                      method: "POST",
                      headers: {
                          "Content-Type": "application/json",
                          "Accept": "application/json",
                          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                      },
                      body: JSON.stringify({deck: this.deck})
                  }
                  fetch("/decks", requestOptions).then(response => response.json()).then(data => window.Turbo.visit(`/decks/${data.id}`))
              } else {
                  const requestOptions = {
                      method: "PATCH",
                      headers: {
                          "Content-Type": "application/json",
                          "Accept": "application/json",
                          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                      },
                      body: JSON.stringify({deck: this.deck})
                  }
                  fetch(`/decks/${this.id}`, requestOptions).then(response => {
                      window.Turbo.visit(`/decks/${this.id}`)
                  })
              }
          },
          existingDeck() {
              return this.deck.id != null
          }
      }
  }).mount('#cards')

});
</script>

app/views/decks/_deck.html.erb
<div id="<%= dom_id deck %>">
  <p>
    <strong>Name:</strong>
    <%= deck.name %>
  </p>

</div>

app/views/decks/_form.html.slim
= content_tag :div, id: 'deck-form',
        class: 'block box',
        data: { id: @deck.id,
                deck: @deck.to_json(except: %i[id created_at updated_at]),
                cards_attributes: @deck.cards.to_json(except: %i[deck_id created_at updated_at]) } do
  #cards
    .columns
      .column.is-two-fifths
        label for="deck-name" class="label subtitle" Deck Name
        input id="deck-name" class="input"  v-model="deck.name"

    h4 class="label" Cards
    .columns v-for="(card, index) in deck.cards_attributes"
      .column v-if="card._destroy == 1"
        | Card will be destroyed
        button.button v-on:click="undoRemove(index)" Undo
      div.column.is-two-fifths.field.has-addons.is-vcentered v-else=""
        p.control.is-expanded
          input.input.is-flex-grow-5 type="text" id='body-{{index}}' class="card-editor" v-model='card.body'
        p.control
          input.input type="text" placeholder="color" v-model="card.color"
        p.control
          button.button.is-disabled.is-rounded.is-outlined
            label.checkbox
              input.checkbox type="checkbox" v-model="card.enabled"
              | Enabled
        p.control
          button.button.is-danger.is-light.is-outlined.is-rounded v-on:click="removeCard(index)" Remove
    .field.is-grouped
      p.control
        button.button v-on:click="addCard" Add Card
      p.control
        button.button.is-primary v-on:click="saveDeck" Save Deck

app/views/decks/edit.html.slim
h1 class="title" Editing Decks
= render "form"

.block.buttons
  = link_to "View this Deck", @deck, class: 'button'
  = link_to "Back to Decks", decks_path, class: 'button'

app/views/decks/index.html.slim
h1.title Decks
div.box id="decks"
  ul.columns.is-flex-wrap-wrap id="deck-list"
    - @decks.each do |deck|
      li.column.is-one-fifth id="deck-#{deck.id}"
        = link_to deck.name, deck, class: 'box has-text-centered has-background-light subtitle'

= link_to 'Create Deck', new_deck_path, class: 'button'

app/views/decks/new.html.slim
h1 class="title" New Deck
= render "form"

.block.buttons
  = link_to "Back to decks", decks_path, class: "button"

app/views/decks/show.html.slim
#app
  h1.title
    = "Deck: #{@deck.name}"
  .box
    h2.subtitle Cards
    hr
    ul.block
      - @deck.cards.each do |card|
        li
          = card.body
    .field.is-grouped.is-grouped-multiline
      p.control
        = link_to "Edit this Deck", edit_deck_path, class: 'button'
      p.control
        = link_to "Back to decks", decks_path, class: 'button'
      p.control
        = button_to "Destroy this Deck", @deck, method: :delete, class: 'button'

app/views/layouts/application.html.slim
doctype html

script
  | window.process = { env: {} }

head
  title BMS Deckbuilder
  meta name="viewport" content="width=device-width,initial-scale=1"
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags

body
  == render 'shared/navbar'
  - if notice
    p.notification.notice.is-primary
      = notice
  - if alert
    p.notification.alert.is-danger
      = alert

  section class="section"
    #container
      = yield

app/views/shared/_navbar.html.slim
nav class="navbar is-link" role="navigation" aria-label="main navigation"
  .navbar-brand
    = link_to decks_path, class: 'navbar-item'
      p class="subtitle has-text-white" BMS Deckbuilder

  .navbar-menu.navbar-end.navbar-item
    .buttons
      - if user_signed_in?
        = button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'button'